### ISSUE TITLE
비밀번호 노출!!

### ISSUE THREAD

**Issue by agrajak** [baki90/Hospital-management#1]
https://github.com/baki90/Hospital-management/blob/e5260897010b89623a37999b220a3c536dbd9749/login.py#L5-L12

**Comment by agrajak** [comment]
여기는 서버 ip랑 id랑 없어서 다행이긴 한데.. 중국 해커들이 깃허브에 있는 소스코드에 있는 password랑 host 크롤링해서 서버 털어서 랜섬웨어 달아놓는 애들 엄청 많음...

**Comment by baki90** [comment]
헐 그럼 이거는 일단 문제 없는 건가??? 어째 이거 오빠 서버잖아 내릴까?!?!?!

2020년 9월 10일 (목) 오후 1:17, Suhyun Jeon <notifications@github.com>님이 작성:

**Comment by baki90** [comment]
아아아아ㅏ 비밀번호 죄송합니다 ㅠㅠ 언넝 수정할게
